### PR TITLE
WIP: add gridspec_kws to FacetGrid

### PR DESCRIPTION
**Pull request by phobson**
Just a quick idea to add a `gridspec_kws` to FactGrid.

Needs:
- [ ] testing
- [ ] docstring
- [ ] documentation

### CODE REVIEW

**Comment by phobson** [comment]
With this small change, you can do:

```python
from io import StringIO

import pandas
import matplotlib.pyplot as plt
import seaborn


datafile = StringIO("""\
location,date,parameter,matrix,units,res
SHP-99-31C,2007-10-17 00:00:00,Iron,WG,ug/L,44000.0
SHP-99-31C,2007-10-17 00:00:00,Arsenic,WG,ug/L,292.1
SHP-99-31C,2009-10-01 00:00:00,Oxidation Reduction Potential,WG,mV,-84.0
SHP-99-31C,2009-10-01 00:00:00,pH,WG,SU,6.57
SHP-99-31C,2009-10-01 00:00:00,Arsenic,WG,ug/L,223.5
SHP-99-31C,2009-10-01 00:00:00,Iron,WG,ug/L,26000.0
SHP-99-31C,2010-10-13 00:00:00,Arsenic,WG,ug/L,239.4
SHP-99-31C,2010-10-13 00:00:00,Iron,WG,ug/L,22000.0
SHP-99-31C,2010-10-13 00:00:00,pH,WG,SU,6.46
SHP-99-31C,2010-10-13 00:00:00,Oxidation Reduction Potential,WG,mV,-80.0
SHP-99-31C,2011-10-05 00:00:00,Iron,WG,ug/L,22000.0
SHP-99-31C,2011-10-05 00:00:00,Arsenic,WG,ug/L,244.0
SHP-99-31C,2011-10-05 00:00:00,Oxidation Reduction Potential,WG,mV,-59.2
SHP-99-31C,2011-10-05 00:00:00,pH,WG,SU,6.5
SHP-99-31C,2012-10-18 00:00:00,Arsenic,WG,ug/L,206.4
SHP-99-31C,2012-10-18 00:00:00,Iron,WG,ug/L,17000.0
SHP-99-31C,2012-10-18 00:00:00,pH,WG,SU,6.75
SHP-99-31C,2012-10-18 00:00:00,Oxidation Reduction Potential,WG,mV,-117.1
SHP-99-31C,2013-10-23 00:00:00,Oxidation Reduction Potential,WG,mV,-95.7
SHP-99-31C,2013-10-23 00:00:00,pH,WG,SU,6.7
""")
df = pandas.read_csv(datafile, parse_dates=['date'])
seaborn.set_style('ticks')
fg = seaborn.FacetGrid(
    data=df, row='units', row_order=['ug/L', 'mV', 'SU'],
    hue='parameter', hue_kws={"marker": ["o", "s", '^', 'd']},
    sharey=False, size=2, aspect=4, margin_titles=True,
    gridspec_kws={'height_ratios': [3.5, 1,1]}  # <---- right here
)
fg.map(plt.plot, 'date', 'res', linestyle='--', marker='o', clip_on=False)
fg.axes.flat[0].set_yscale('log')
fg.axes.flat[-1].set_ylim(bottom=4.75, top=9)
```
test

**Comment by phobson** [comment]
Whoops -- not compatible with matplotlib 1.1

<knannnnnn.jpg>

**Comment by phobson** [comment]
I kind of want to reopen this. Maybe provide a warning when we can't use gridspec?

**Comment by mwaskom** [comment]
Does matplotlib 1.1 raise? or just ignore.

**Comment by mwaskom** [comment]
Catching the error, firing a warning, and rerunning the code without gridspec would look a little ugly but from the user perspective I'm fine with it.

**Pull request closed without merging**
