### PR TITLE
Added checks for input types for distributions.jointplot

### PR DESCRIPTION
**Pull request by Prikers**
Added a couple of checks for `distributions.jointplot`:
* Check if `data` is a `pandas.DataFrame` (if passed)
* Check if `x` and `y` are valid column names in `data`

Added a test unit as well

### CODE REVIEW

**Comment by Prikers** [comment]
I am not sure to understand why `make lint` is failing for python 2 here. Anyone could help?

**Comment by mmagnuski** [comment]
Travis tells you why:
`seaborn/tests/test_distributions.py:136:1: W293 blank line contains whitespace`

**Comment by Prikers** [comment]
(feeling stupied...) I was not able to find the actual error message from Travis. Thanks. All checks are passed now. This should fix #1204

**Comment by mmagnuski** [comment]
You'll have to wait for @mwaskom to review and accept.
I'm +1 on this but I'm just a passerby. :)

**Comment by mwaskom** [comment]
There are a few problems with this implementation.

First, the input validation should happen in `JointGrid`, not `jointplot`.

Second, this PR reduces flexibility in a few ways:

- Currently it's not required that `data` be a `DataFrame`, it just has to be any object that implements `.get`. While not fully documented, that flexibility should be maintained.
- Currently, you can pass one variable as a reference to a field in `data` and one variable as an array. Or two variables as arrays and pass `data` (I'm not sure when this would be useful, but it's possible). The correct way to do the input validation would be to check if the x and y variables are string types (accounting for Py 2/3 compatibility) after trying to get them from `data`.

**Comment by Prikers** [comment]
Sorry about that! I am still trying to get more familiar with the source code. I moved the input checks to `JointGrid`.

However as of today, the first checks are like this: 
```python
if data is not None:
    if x in data:
        x = data[x]
```
so if we pass a `DataFrame` in `data` and an `array` in `x` we get a `TypeError: unhashable type:  'numpy.array'`. That is why I thought we could not have those mixed-type situations. Therefore I moved the `string_type` verification upfront the verification `if x in data`.  
Does it cover all situations?

**Comment by Prikers** [comment]
Sorry about that! I am still trying to get more familiar with the source code. I moved the input checks to `JointGrid`.

However as of today, the first checks are like this: 
```python
if data is not None:
    if x in data:
        x = data[x]
```
so if we pass a `DataFrame` in `data` and an `array` in `x` we get a `TypeError: unhashable type:  'numpy.array'`. That is why I thought we could not have those mixed-type situations. Therefore I moved the `string_type` verification upfront the verification `if x in data`.  
Does it cover all situations?

**Comment by mwaskom** [comment]
Hm good point, I was thinking of the way things are handled in the categorical plots, which I now view as the best way of doing things: https://github.com/mwaskom/seaborn/blob/6ddedad5c9e734e4bb8751adb4efa851cc323b00/seaborn/categorical.py#L140

**Comment by mwaskom** [comment]
There were a couple of other issues and it was easiest to just demonstrate rather than keep nitpicking: #1213. Thanks for catching.

**Pull request closed without merging**
