### PR TITLE
PDF backend not compatible with using get_renderer

### PR DESCRIPTION
**Pull request by blaiseli**
I introduced a check on the backend, so that PDF backend can still be used.

See https://github.com/mwaskom/seaborn/issues/1262

### CODE REVIEW

**Comment by mwaskom** [comment]
I'd like to understand this problem a bit more before merging any changes. The following code works perfectly fine for me:

```python
import numpy as np
import seaborn as sns
x = np.random.randn(10, 10)
g = sns.clustermap(x)
g.savefig("test.pdf")
```

**Comment by PaulRivaud** [comment]
I am encountering a similar issue.
I work on headless servers and need to use non-interactive backends.
Some of my imports using python 3.6:
```python
import matplotlib
matplotlib.use('PDF')
import matplotlib.pyplot as plt
import seaborn as sns
```
Generating a pdf:
```python
ax = sns.heatmap(df, annot=True, fmt=".0%", cmap=params['classify']['cell_classification']['table_plot_cmap'])

plt.xlabel('Predicted sample')
plt.ylabel('Cells origin')
plt.title('Cell classification accuracy')
plt.xticks(rotation='vertical')
plt.yticks(rotation='horizontal')
plt.grid(False)
plt.tight_layout()

plt.savefig(os.path.join(dir_, 'cell_classification_table.pdf'))
```

Leads to this error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paul/Documents/graham/methods/Classify.py", line 182, in ClassifyCells
    plot_cells_table(Res, labels, params)
  File "/Users/paul/Documents/graham/methods/Classify.py", line 144, in plot_cells_table
    ax = sns.heatmap(df, annot=True, fmt=".0%", cmap=params['classify']['cell_classification']['table_plot_cmap'])
  File "/Users/paul/anaconda/envs/py36/lib/python3.6/site-packages/seaborn/matrix.py", line 528, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/Users/paul/anaconda/envs/py36/lib/python3.6/site-packages/seaborn/matrix.py", line 315, in plot
    ax.figure.draw(ax.figure.canvas.get_renderer())
AttributeError: 'FigureCanvasPdf' object has no attribute 'get_renderer'
```

**Comment by mwaskom** [comment]
That doesn't really answer the question of what is breaking and what the best way to get it to work is. Calling `plt.draw()`, which has its own problems, isn't it.

**Comment by blaiseli** [comment]
I finally managed to create a minimal example illustrating my problem:

```python
import numpy as np
import matplotlib as mpl

# use_pdf = False
use_pdf = True
if use_pdf:
    mpl.use("PDF")

import matplotlib.pyplot as plt

# Suppose we need usetex, for instance to use colours in text
# (see https://stackoverflow.com/a/42768093/1878788)
from matplotlib.backends.backend_pgf import FigureCanvasPgf
mpl.backend_bases.register_backend('pdf', FigureCanvasPgf)
TEX_PARAMS = {
    "text.usetex": True            # use LaTeX to write all text
}
mpl.rcParams.update(TEX_PARAMS)

from matplotlib.backends.backend_pdf import PdfPages

import pandas as pd

from seaborn import matrix as mat


rs = np.random.RandomState(sum(map(ord, "heatmap")))
x_norm = rs.randn(4, 8)
letters = pd.Series(["A", "B", "C", "D"], name="letters")
df_norm = pd.DataFrame(x_norm, index=letters)

def test_heatmap(data):

    g = mat.heatmap(data)
    plt.savefig("/tmp/test_heatmap.pdf")

def test_pdfpages(data):

    pp = PdfPages("/tmp/test_pdfpages.pdf")
    data.T.plot("A", "B")
    plt.savefig(pp, format="pdf")
    data.T.plot("A", "C")
    plt.savefig(pp, format="pdf")
    pp.close()


if use_pdf:
    test_pdfpages(df_norm)
    # No error
    test_heatmap(df_norm)
    # AttributeError: 'FigureCanvasPdf' object has no attribute 'get_renderer'
else:
    test_heatmap(df_norm)
    # No error
    test_pdfpages(df_norm)
    # ValueError: filename must be a path or a file-like object
```

There's an incompatibility between using tex to render text and using `PdfPages` to produce multipage pdf documents that is solved when using "PDF" as backend, but this causes the `AttributeError` in `seaborn.matrix._HeatMapper.plot`.

**Comment by mwaskom** [comment]
I don't seem to have any problem using PdfPages without your change:

```python
from matplotlib.backends.backend_pdf import PdfPages
with PdfPages('/Users/mwaskom/Desktop/test.pdf') as pdf:
    g = sns.clustermap(corrmat, rasterized=True, center=0, vmax=.5, cmap="vlag")
    pdf.savefig(g.fig)
```

This runs without error and generates a nice plot.

**Comment by mwaskom** [comment]
Oh I just saw that you have some problem with tex too.

**Comment by blaiseli** [comment]
@mwaskom I think the real issue here is that to use tex and PdfPages at the same time, I need `mpl.use("PDF")`, which is incompatible with `heatmap`. Now what is the goal of https://github.com/mwaskom/seaborn/commit/7b445822bc4c1edf22c8e8e11f67e632ffb90f86? Is it useful when backend is "PDF"?

**Comment by mwaskom** [comment]
> Now what is the goal of 7b44582? 

See https://github.com/mwaskom/seaborn/pull/1236

**Comment by blaiseli** [comment]
I'm not sure I fully grasp the problem, but it seems to me that not all backends need this switch to `ax.figure.draw`. Am I correct that keeping `plt.draw` only when the backend is "PDF" (as I tried to do in my pull request) will not interfere with the resolution of this "GUI-backend"-related issue?

**Comment by mwaskom** [comment]
No, I would like to avoid `plt.draw` and use the object-oriented interface.

**Pull request closed without merging**
