### PR TITLE
DOC: minor fixes

### PR DESCRIPTION
**Pull request by MaozGelbart**
This PR fixes an internal broken link in the tutorial and a typo. It's great to see 0.11 RC!

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks for catching! I think these should be 

```
:doc:`$PROSE TERM <tutorial/function_overview>
```

Using :doc: rather than :ref: will avoid the annoying bug where the page is not vertically aligned properly after you click on the link (which i think I have tracked down to an issue in the specific theme). But I believe (not certain) you can only link to pages that way, and not to sections.

**Comment by MaozGelbart** [comment]
Thanks, I've updated accordingly.

**Comment by MaozGelbart** [comment]
Now also addresses the first action item in #2244 but not [https://github.com/mwaskom/seaborn/issues/2244#issuecomment-686845902](https://github.com/mwaskom/seaborn/issues/2244#issuecomment-686845902), since it seems to require css knowledge which I'm not familiar with.

**Comment by mwaskom** [comment]
Thanks!

**Pull request merged**
