### PR TITLE
[v0.11] Vendor the Version package, use it instead of distutils

### LINKED ISSUE #2724: DeprecationWarning with the latest setuptools
Starting with `setuptools==60.0.0` there's a `DeprecationWarning` for distutils version classes: https://github.com/pypa/setuptools/commit/1701579e0827317d8888c2254a17b5786b6b5246

This leads to a warning in seaborn:
```bash
$ pip install -U 'setuptools>=60' seaborn
$ python -We -c 'import seaborn'         
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.7/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/venv/lib/python3.7/site-packages/seaborn/rcmod.py", line 82, in <module>
    if LooseVersion(mpl.__version__) >= "3.0":
  File "/venv/lib/python3.7/site-packages/setuptools/_distutils/version.py", line 57, in __init__
    stacklevel=2,
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

I see that this has probably been fixed by #2466 on master. But this change hasn't been released yet. Maybe this can be a reason to realease a new patch version sooner than later? Unfixable warnings can have an impact on many CI/CD setups.

### PR DESCRIPTION
**Pull request by Stannislav**
Fixes #2724

Cherry-picked a0f7bf8 / #2659 as discussed in #2724

### CODE REVIEW

**Comment by Stannislav** [comment]
As discussed in #2724

**Comment by mwaskom** [comment]
Thanks @Stannislav! Looks like CI is [not set up to run](https://github.com/mwaskom/seaborn/blob/v0.11/.github/workflows/ci.yaml#L7) on PRs against the `v0.11` branch; would you mind adding that as part of this PR?

**Comment by Stannislav** [comment]
@mwaskom has the v0.11 branch been tested recently? Not sure some failing tests have to do with the changes in this PR. I'll try and look into the details tonight.

**Comment by mwaskom** [comment]
> @mwaskom has the v0.11 branch been tested recently? Not sure some failing tests have to do with the changes in this PR

no, I wasn’t expecting to do an 0.11.3 so it’s been dormant for a while. I don’t think the test failures are caused by this pr; matplotlib broke some tests with their 3.5 release (by changing an API that only the tests hit); they’ve also added some deprecation warnings that get a lot of false alarms and add noise.

I’m less sure what’s happening with the failing setup in the doc build, but also doubt this PR caused it.

**Comment by Stannislav** [comment]
@mwaskom the docs build is failling because of `sphinx_bootstrap_theme==0.7.1` in `docs/requirements.txt`. The problem is that this package is using `setup(use_2to3=True, ...)` in `setup.py`, which [was removed in `setuptools>=58`](https://setuptools.pypa.io/en/latest/history.html#v58-0-0). To reproduce
```sh
pip install 'setuptools>=58'
pip install 'sphinx_bootstrap_theme==0.7.1'
```

The [next higher version](https://pypi.org/project/sphinx-bootstrap-theme/#history) is `sphinx_bootstrap_theme==0.8.0` and it fixes the error. Any reason not to bump? I see it was updated on master in #2704.

**Comment by mwaskom** [comment]
> The [next higher version](https://pypi.org/project/sphinx-bootstrap-theme/#history) is sphinx_bootstrap_theme==0.8.0 and it fixes the error. Any reason not to bump? I see it was updated on master in https://github.com/mwaskom/seaborn/pull/2704.

Ah yeah, that sounds right.

**Comment by Stannislav** [comment]
@mwaskom I bumped `sphinx-bootstrap-theme` and cherry-picked #2690 to try and fix the tests after matplotlib 3.5 upgrade. Is it possible to re-trigger the CI to try and test?

**Comment by mwaskom** [comment]
Thanks @Stannislav sorry this is turning into such a headache for you. I'm not sure why new contributors need every PR push to be approved for CI (rather than just the first one).

**Comment by Stannislav** [comment]
Hey @mwaskom no worries. Maybe the approval is needed because it's a forked branch.

Anyway, a small change adopted from master (from #2413) fixed the test locally, so we can try to retest.

**Review by mwaskom — APPROVED** [review]

**Comment by mwaskom** [comment]
> Maybe the approval is needed because it's a forked branch.

Yeah — I think it's to stop people from opening a PR that mines crypto in CI, so it makes sense to require approval for the first run, but I wish there were a checkbox to say "run CI on subsequent pushes for this PR".

In any case, everything looks good here now — thanks!

**Comment by EwoutH** [comment]
Could a new release on the v0.11.x branch be tagged, which includes this change?

**Pull request merged**
