### PR TITLE
Change MPL keyword 'axisbg' to 'facecolor'

### PR DESCRIPTION
**Pull request by JWarmenhoven**
#1108

### CODE REVIEW

**Comment by mwaskom** [comment]
This change isn't sufficient because it will break on older versions of matplotlib. It's necessary to maintain backwards compatibility.

**Comment by JWarmenhoven** [comment]
Hmm...yeah I realized that after testing some more.

**Comment by mwaskom** [comment]
I don't actually know why the dendrogram axes are being set to white background + fully despined + no ticks; it would be easier just to do `set_axis_off()`.

**Comment by JWarmenhoven** [comment]
Yes, a quick test shows that `set_axis_off()` on the col/row dendrogram axes appears to do the trick. But as you mentioned, there may be another use case where the background of the axes need to be set to white?

**Comment by mwaskom** [comment]
No obvious reasons come to mind, and `set_axis_off` will work better in other circumstances, e.g. when you want a transparent figure background.

**Pull request closed without merging**
