### PR TITLE
Add seaborn.crayons and crayon_palette to use Crayola colors

### PR DESCRIPTION
**Pull request by mwaskom**
When I was a kid we didn't even *have* 120 Crayola colors.

```python
sns.palplot(sns.crayon_palette(["Denim", "Fern", "Brick Red",
                                "Plum", "Sunglow", "Cerulean"]))
```

screenshot 2015-03-25 18 58 54

Thanks to Karl Broman's [crayonJS](https://github.com/kbroman/crayonsJS) library for the idea.

### CODE REVIEW

**Comment by mmagnuski** [comment]
This is perfect! :smile:

**Comment by phobson** [comment]
waaaat! :+1:

**Comment by nirum** [comment]
time for a makeover :nail_care:

**Comment by mwaskom** [comment]
I expect to see some Tickle Me Pink plots at your defense, @nirum

**Comment by vsoch** [comment]
:+1:

**Pull request merged**
