### PR TITLE
Jointgrid and dependency fix

### PR DESCRIPTION
**Pull request by ravimakhija**
This PR supersedes PR #1356 which addressed issue #1352 as well as two dependency issues found along the way. This pull request was created to organize the three commits in a feature branch. More details can be found in the original PR, #1356.

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks. I don’t think I understand the motivation for adding a call to ‘plt.figure’ in every docstring example. It adds a lot of noise.

**Comment by ravimakhija** [comment]
I agree that it does add some noise. I will share my train of thought and welcome any ideas on improving the approach. 

To take a particular case of where doctest was failing: consider the pointplot function. The second example uses the `hue=smoke` parameter in its call. I believe the use of that parameter (there may be other causes as well) changes the _internal state of the Matplotlib objects/context_ in such a way that the error-causing code of Matplotlib v2.1.1 (e.g. the code that does not handle the numpy array comparisons) ends up running for subsequent seaborn plot calls, which are affected by that state. Therefore, the third example fails. 

If the second example of pointplot is removed and the third example remains, it will no longer fail at the point of the third example because the first test does not change the state in such a way that triggers the error-causing code of Matplotlib. However, the fourth example will probably fail since the third example does change the state in this way. 

If there is another way (e.g. perhaps a seaborn or matplotlib option that can be set) for this _internal state_ to be cleared after each example, then I think that would also work and perhaps be cleaner. That is essentially what plt.figure() is doing currently, and it is assigned to a variable just to avoid returning the figure, since then it will be expected by the doc test. 

Alternatively, if you don't mind the tests failing for only Matplotlib v2.1.1, then the original doctest code will also likely work (since as mentioned the Matplotlib issue was addressed after v2.1.1).

**Comment by mwaskom** [comment]
Can you please link to the matplotlib issue describing the bug that you say only exists on 2.1.1?

The problem *arises* in the doctests because when pytest executes them, the state of the matplotlib figure persists across each chunk (unlike what happens when the docs themselves are actually built). I'm [not sure](https://stackoverflow.com/questions/47514043/use-pytest-fixture-for-each-chunk-of-doctests-in-a-single-docstring) if there's a way to avoid this. So what's happening is that most or all of the doctest examples for a given function are actually being plotted onto the same axes.

But it should in general be possible to draw multiple, e.g., point plots onto the same axes. So if the doctests are failing when they try to do that, it's not really a problem with the doctests so much as seaborn/matplotlib, and your approach of instantiating a separate figure for each chunk simply hides the problem.

If it's actually a bug in matplotlib that's isolated to a specific minor version, then the Travis build can be configured not to use that version and it will just be a transient nuisance for some users.

**Comment by mwaskom** [comment]
I suspect it's this: https://github.com/matplotlib/matplotlib/issues/10053

**Comment by ravimakhija** [comment]
Indeed, that looks like the issue. I had found the issue via PR matplotlib/matplotlib#10031, where there is a commit titled "Make comparison work with arrays" and also where user dstansby comments:

> The problem is the original 'color comparison' code in the figure legend method didn't allow for colors to be numpy arrays. Long term I think this should be avoided by a general function for comparing colors, which I've put in #10032

**Comment by mwaskom** [comment]
OK if it's a problem on a specific version of matplotlib and will be fixed in 2.1.2 then I think it's best to just skip testing on that version.

I've also opened an [issue on pytest](https://github.com/mwaskom/seaborn/blob/master/doc/sphinxext/plot_directive.py) looking for guidance on configuring a fixture to properly close figures between each chunk the way that the matplotlib sphinx extension does when actually building the docs.

**Comment by mwaskom** [comment]
Thanks @ravimakhija. I cherry picked your `JointGrid` commit to #1383 but I'm skipping the changes to the tests for now because the current version of matplotlib no longer causes errors and the right way to handle the figure cleanup is through a `pytest` plugin.

**Pull request closed without merging**
