### PR TITLE
DOC different metrics for axes in clustermap

### PR DESCRIPTION
**Pull request by jnothman**
I think this brief comment may help users even conceive of the idea that rows and columns need not cluster with the same metric.

### CODE REVIEW

**Comment by mwaskom** [comment]
That phrasing strikes me as misleading. It suggests that you would pass the same kind of argument to row_linkage as you would to metric.

**Comment by mwaskom** [comment]
OK, that's a little better, but something still strikes me as weird about introducing the idea in the parameter doc for `metric`. I'll think about what seems best.

**Comment by jnothman** [comment]
I propose this having almost submitted a new issue requesting support for
multiple metrics. The first place I looked for the existence of that
feature was the metric parameter description. I don't think there is any
way to make this feature more obvious.

**Comment by mwaskom** [comment]
mk.

**Comment by mwaskom** [comment]
Thanks @jnothman this is fine

**Pull request merged**
