### PR TITLE
Added option for ci to be a callable.

### PR DESCRIPTION
**Pull request by msf235**
Added the option for ci to be a callable in relational.py. If ci is a callable, it should take a list of values representing multiple observations of the ``y`` variable at the same ``x`` level and return a list [lower_bound, upper_bound] where lower_bound is the lower value for the shaded region and upper_bound is the upper value for the shaded region. ci can also return a different length-two array-like object. A ValueError exception is raised if ci is callable but doesn't satisfy these conditions. I also modified the documentation to reflect this change. Also fixed a comment typo.

Why I think this is a good idea: (1) It mirrors the functionality of estimator, (2) it doesn't change the way the code works when ci isn't passed as a callable, and (3) it allows the user to make error bars based off of any criteria they choose.

### CODE REVIEW

**Comment by msf235** [comment]
Note that I have not used coverage in the past and so didn't implement my own tests here. I am happy to do that if it is requested.

**Comment by mwaskom** [comment]
Could you comment on #2403, which lays out plans for expanding the flexibility of the error bar plotting? Would you still find a fully generic callable argument necessary if that scheme is implemented? It would significant additional complexity (both implementational and explanatory).

**Comment by msf235** [comment]
I can join the discussion there. My hope was that adding the option for ci to be a callable wouldn't add undue complexity. It seems to be analogous to passing a callable for estimator (which is currently implemented), the only difference being that instead of returning one value the callable should return two. As such, I was hopeful that the approach needed to, say, document this behavior was at least partly worked out already. In my changes to the documentation I followed the template established by the documentation for estimator.

My personal use case is that I am creating error bars by fitting a gamma distribution. I'm doing this because I have data that I know is bounded and highly skewed, and want to take that knowledge into consideration when creating error bars. These are not standard gamma distributions either -- they are shifted and reflected. I believe this is the "proper" approach from a Bayesian perspective -- to choose a prior that captures the basic elements of the data. Regarding #2403, I don't see any bigram approach really fitting my use case.

My perspective is that, if a general callable is implemented, it takes the pressure off of developing a progressively more complicated interface for error bars, which may happen if users increasingly ask for new ways to use error bars (such as if people follow the Bayesian perspective of fitting generic distributions to create these error bars). Then the interface could be kept simple in a way that fits "most" use cases, and the callable is always available to satisfy the remaining cases. That said, a bigram is probably not too complicated and may fit most people's use cases.

For implementing multiple error bars on the same plot, one could potentially pass a list of things for ci. This could, for instance, be a list of callables, each callable corresponding to one error bar. This method could produce an arbitrary number of arbitrary error bars.

So that's my plug. I'll follow along with #2403 and comment where I think I can contribute.

**Comment by mwaskom** [comment]
Out of curiosity, how different are the bootstrap intervals from your bespoke intervals?

**Comment by msf235** [comment]
Here is an example of the difference I see. The first plot shows all the individual realizations, the second plot uses ci=95, and the third uses a (reflected and shifted) gamma distribution fit to make the error bars.
seaborn_demo
I'm not sure why the error bars are so small when ci=95. It could be I'm doing something wrong. Here is a csv file with the data: [data file here](http://s000.tinyupload.com/?file_id=00648673576752029569)

**Comment by mwaskom** [comment]
> I'm not sure why the error bars are so small when ci=95. It could be I'm doing something wrong. 

It looks like your error bars are representing the spread of the distribution of observations, not a proper confidence interval (i.e. the spread of the bootstrap replicates of the estimator), so that discrepancy makes some sense. In the new scheme, the `pi` method will be a nonparametric approach for accomplishing that, but in this example (where you have small N) it would work poorly relative to your Bayesian method.

**Comment by mwaskom** [comment]
Closed by #2407

**Pull request closed without merging**
