### PR TITLE
Allow pandas objects to flow through tsplot

### PR DESCRIPTION
**Pull request by clearf**
I'm submitting this PR to try to kickstart the conversation around https://github.com/mwaskom/seaborn/issues/242. It's a surprisingly annoying error. 

My understanding is that, while matplotlib doesn't handle all instances of pandas objects correctly, it definitely does not handle processing dates passed merely as values correctly, going so far as to throw an overflow error if sns.tsplot is called while trying to represent the data as dates: 

    fig, ax = plt.subplots()
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y.%m.%d'))
    ax.xaxis_date()
    fig.autofmt_xdate()
    sns.tsplot(data=ph, time='signal_date',  
                        value='cum_ret', unit='key', condition='ticker', 
                        estimator=np.mean, interpolate=True, ax=ax)
    plt.show() # Throws overflow error. 

I'm not sure if other things break with this PR, but I do know that at least one thing gets fixed. 

And relying on matplotlib to implement doesn't seem great either – the initial conversation on this was 3 years ago, and the last comment 6 months ago. 

What's the best way to move forward on this?

### CODE REVIEW

**Comment by clearf** [comment]
@mwaskom Hi Michael, just wanted to make sure this PR was pointing to the correct repository, etc. Would love to get a conversation started about this issue. 

Thanks,
Chris

**Comment by mwaskom** [comment]
Sorry, I have been very busy with actual responsibilities lately and have had basically no time for any real thought about seaborn.

My basic position on this is that I am apprehensive about making any changes to `tsplot` until it can be refactored and rigorously tested. With that said, your change is quite small, so if that's really all that it takes to make it work, I am open to it.

The problem is that it is unclear what this change might disrupt, due to the lack of unit tests. So it will be important to manually test the different code paths rigorously to check that everything works as expected. The best place to start there would be with this [old notebook](https://github.com/mwaskom/seaborn/blob/v0.2/examples/timeseries_plots.ipynb), which i the first thing that comes to mind in terms of a single example of all the various things `tsplot` can do. If you can modify the example datasets to use datetime data for the time variable and everything runs smoothly and looks good, then it will provide some confidence. (Sorry in advance if the notebook doesn't run out of the box with modern libraries, it's a bit old, but I *think* it should either work or just require a few small tweaks).

This may be more work than you were expecting, sorry. The internals of `tsplot` are very old and existed before I had any expectation that seaborn would be something anyone else would want to use, much less contribute to.

**Comment by clearf** [comment]
Great, I'll take a look. Thanks.

**Comment by eyadsibai** [comment]
It would be nice to have this pull request in master...

**Pull request closed without merging**
