### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tanujdhiman**
Add License to Readme

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks @tanujdhiman but as the license is packaged in the source distribution I don't think it needs to be duplicated in the README.

**Comment by tanujdhiman** [comment]
Yes, @mwaskom.
Actually, Readme.md is for explaining things for a particular repository. So, if we have provide the License in this Readme then user just come to know this library issued by which License. 
Hope you understand !!
Thanks

**Comment by mwaskom** [comment]
> So, if we have provide the License in this Readme then user just come to know this library issued by which License otherwise we have to find out the file in a large bunch.

That information is already present in both the Github UI and as a badge in the README, so anyone looking at the file in a rich text interface will see it. Those who are stubbornly committed to plain text will not have to look through a large bunch of files because the license file has the canonical name (much like README).

> Examples like - Tensorflow etc.

Libraries can choose to duplicate or not duplicate information. Tensorflow doesn't have the license badge. I also suspect that, as a project backed by a large corporation they feel motivated to boost the signal on their liberal open source license.

**Comment by tanujdhiman** [comment]
Okay. Thanks

**Pull request closed without merging**
