### PR TITLE
Make all links possible use https://

### PR DESCRIPTION
**Pull request by hartwork**
Related to #1984

PS: For colorbrewer2 https is not yet available, so I raised awareness upstream at https://github.com/axismaps/colorbrewer/issues/28 .

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks; can you run `make linkcheck` and paste the output here?

**Comment by hartwork** [comment]
> Thanks; can you run `make linkcheck` and paste the output here?

I have checked all links that I changed, manually.

I have spent more than an hour now on getting `make linkcheck` to run: it's not exactly fun and not finished. Is it necessary or could you run it for me with the new changes checked out, instead?
If it's needed for changes like this, maybe it can be made part of the CI to ease contribution?

**Comment by hartwork** [comment]
PS: Does this help?
```console
# for i in $(git diff master https-links | grep '^\+' | grep -o "https://[^ \"'>)]\+" | sort -u); do echo "$(timeout 2s wget -q -O/dev/null "$i" && echo 'PASS  ' || echo 'FAIL') -- $i"; done
PASS   -- https://docs.scipy.org/doc/numpy/
PASS   -- https://docs.scipy.org/doc/scipy/reference/
PASS   -- https://matplotlib.org/
PASS   -- https://numpy.org/
PASS   -- https://pandas.pydata.org/
PASS   -- https://seaborn.pydata.org/examples/different_scatter_variables.html
PASS   -- https://seaborn.pydata.org/examples/errorband_lineplots.html
PASS   -- https://seaborn.pydata.org/_static/different_scatter_variables_thumb.png
PASS   -- https://vita.had.co.nz/papers/tidy-data.html
PASS   -- https://www.cns.nyu.edu/~mwaskom
PASS   -- https://www.hsluv.org/
PASS   -- https://www.scipy.org/
PASS   -- https://www.sphinx-doc.org/
PASS   -- https://www.statsmodels.org/
PASS   -- https://www.statsmodels.org/stable/
```

**Comment by mwaskom** [comment]
Thanks — not sure why you had trouble with `make linkcheck` but your bash-fu accomplishes the same purpose. (It's not part of the regular CI build because I think this might be the first PR to actually change links in the docs).

**Pull request merged**
