### PR TITLE
Add annotation support to clustermap. Fixes #1752.

### LINKED ISSUE #1752: rows/cols of the annotation dataframe are not ordered in clustermap
I'm trying to annotate a clustermap but seaborn doesn't apply the row/column reordering of the data matrix to the annotation dataframe. 

So I reorder the annotation dataframe myself in a second clustermap call, but there is something wrong:

```python
cm = sns.clustermap(overlap, standard_scale=1, cmap='Reds')
overlap = overlap.iloc[cm.dendrogram_row.reordered_ind, 
                       cm.dendrogram_col.reordered_ind]
sns.clustermap(overlap, standard_scale=1, cmap='Reds', annot=overlap)
```

Here is the output:

image

Zeros at the bottom right corner do not look correct. Any suggestions? 

Wouldn't it be easier to just reorder rows/cols of the annotation df based on the indices of the data matrix?

### PR DESCRIPTION
**Pull request by gokceneraslan**

### CODE REVIEW

**Comment by gokceneraslan** [comment]
Here is how it works:

```python
import seaborn as sns
import pandas as pd
import numpy as np

np.random.seed(123)
x = np.random.binomial(10, 0.2, size=(10,10))
sns.clustermap(x, annot=True)
sns.clustermap(x, annot=x)
sns.clustermap(x, annot=False)
sns.clustermap(x, annot=None)
```

image

image

image

image

**Comment by gokceneraslan** [comment]
Any news?

**Comment by gokceneraslan** [comment]
I rebased this against master, fyi.

**Comment by mwaskom** [comment]
Sorry that I don't have time to give detailed guidance on submitting PRs, but generally I won't look at new features closely until they have tests.

**Comment by gokceneraslan** [comment]
Thanks!

**Pull request closed without merging**
