### PR TITLE
setup.py: Update required dependency versions

### PR DESCRIPTION
**Pull request by EwoutH**
Updates the required versions of the numpy, pandas, matplotlib, scipy and statsmodels.

All minimum required versions support Python 3.7, so full Python 3.7 support is remained.

Updating the minimum required versions allows to use newer and more performant features and remove depreciated functions.

**Release notes**

- Numpy: [1.17](https://numpy.org/doc/stable/release/1.17.0-notes.html), [1.18](https://numpy.org/doc/stable/release/1.18.0-notes.html), [1.19](https://numpy.org/doc/stable/release/1.19.0-notes.html), [1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html), [1.21](https://numpy.org/doc/stable/release/1.21.0-notes.html), 
- Pandas: [0.25](https://pandas.pydata.org/docs/whatsnew/v0.25.0.html), [1.0](https://pandas.pydata.org/docs/whatsnew/v1.0.0.html), [1.1](https://pandas.pydata.org/docs/whatsnew/v1.1.0.html), [1.2](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html), [1.3](https://pandas.pydata.org/docs/whatsnew/v1.3.0.html)
- Matplotlib: [3.1](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.1.0.html), [3.2](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.2.0.html), [3.3](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.3.0.html), [3.4](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html)
- Scipy: [1.3](https://docs.scipy.org/doc/scipy/release.1.3.0.html), [1.4](https://docs.scipy.org/doc/scipy/release.1.4.0.html), [1.5](https://docs.scipy.org/doc/scipy/release.1.5.0.html), [1.6](https://docs.scipy.org/doc/scipy/release.1.6.0.html), [1.7](https://docs.scipy.org/doc/scipy/release.1.7.0.html)
- Statsmodels: [0.10](https://www.statsmodels.org/dev/release/version0.10.html), [0.11](https://www.statsmodels.org/dev/release/version0.11.html), [0.12](https://www.statsmodels.org/dev/release/version0.12.html)

Especially the newer minimum Matplotlib version might be interesting, with [Secondary x/y Axis support](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.1.0.html#id4) and [Legend for scatterplots](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.1.0.html#id6) in Matplotlib 3.1 and significant Figure and Axes creation in Matplotlib 3.3 and 3.4.

### CODE REVIEW

**Comment by mwaskom** [comment]
-1 here, it is too aggressive. Per [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), new versions of seaborn should be compatible with versions of dependencies released up to two years prior. And seaborn tends to be a little bit more conservative than that as I don't have the bandwidth to do micro-version bugfix releases.

**Comment by EwoutH** [comment]
Thanks for getting back. Would you like a dependency bump in which all minimum dependency versions are at least two years old?

**Comment by mwaskom** [comment]
I've been bumping minimal deps as needed on the `nextgen/main` branch, I think they're about one minor version behind these right now. In general I don't think it's necessary to bump versions for no reason.

> I think users working with packages older than this also won't be updating their seabornd 

In most cases, that's probably right. But one thing to keep in mind is that it's easier to update seaborn than numpy/pandas/scipy, because those are more likely be used within complicated systems. So, e.g. companies with a single-supported-version policy might be conservative about updating core libraries (doing so would demand a lot of testing) but more amenable to updating libraries like seaborn where any broken code is likely to live in notebooks without dependencies.

**Comment by EwoutH** [comment]
Thanks for the extensive explanation, it makes sense. I will close this PR.

**Pull request closed without merging**
