### PR TITLE
Add compatability for IPython3/4/Jupyter in functions that use widgets

### LINKED ISSUE #699: choose_colorbrewer_palette error with ipython 4 and jupyter
Dear all,

if I run this code

```python
import seaborn as sns
sns.choose_colorbrewer_palette('qualitative')
```

it returns this error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b05cf0dd3d2a> in <module>()
      1 import seaborn as sns
----> 2 sns.choose_colorbrewer_palette('qualitative')

/usr/local/lib/python2.7/dist-packages/seaborn/palettes.py in choose_colorbrewer_palette(data_type, as_cmap)
   1011 
   1012     """
-> 1013     from IPython.html.widgets import interact, FloatSliderWidget
   1014 
   1015     if data_type.startswith("q") and as_cmap:

ImportError: cannot import name FloatSliderWidget 
```

this happened just after updating to the new IPython 4 and Jupyter. 

I understand that the IPython.html.widgets have been moved to the new package ipywidgets.
I installed it and I got the same error. Then I replaced all "FloatSliderWidget" in "palettes.py" for "FloatSlider" and it worked!

I hope this is helpful

Regards

### PR DESCRIPTION
**Pull request by mwaskom**
Closes #699

### CODE REVIEW

**Comment by mwaskom** [comment]
cc @wrobstory is this the right approach for compatibility with different places IPython widgets have lived? (Specifically [here](https://github.com/mwaskom/seaborn/pull/740/files#diff-c446aafade3a0f922242511fd6dcdd4fR7))

**Comment by wrobstory** [comment]
Oof, I'm not familiar with https://github.com/mwaskom/seaborn/pull/740/files#diff-c446aafade3a0f922242511fd6dcdd4fR14

It looks ok to me, but might want to summon @minrk to this thread.

**Comment by minrk** [comment]
Looks right to me.

**Comment by mwaskom** [comment]
Thanks Min!

**Pull request merged**
