### PR TITLE
Test against pandas 0.20.0rc2

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'm pretty sure [these](https://travis-ci.org/mwaskom/seaborn/jobs/228790701) failures are unrelated to RC2.

**Comment by mwaskom** [comment]
Hm. Those are new.

**Comment by mwaskom** [comment]
Looks like matplotlib has ticked up to 2.0.1 since your last PR. Could be the cause. Interesting that it doesn't fail on the minimal versions build.

**Comment by TomAugspurger** [comment]
> Looks like matplotlib has ticked up to 2.0.1 since your last PR.

Good catch. I'm able to reproduce the failures locally with matplotlib 2.0.1 (regardless of pandas rc2)

**Comment by mwaskom** [comment]
Oh goodie.

**Comment by mwaskom** [comment]
If that environment is handy can you run [this example](http://seaborn.pydata.org/examples/factorplot_bars.html) in it and see what looks different?

**Comment by TomAugspurger** [comment]
2.0.0:
mpl200

2.0.1:

mpl201

Differences are in the errorbars: The top of `second, male` moved down and all of `third, female` moved down

**Comment by mwaskom** [comment]
Hm weird, a little movement of the errorbars make sense because of bootstrapping, but the test failures are about the bottom of the bars not being a 0 on the quantitative axis, which we're not seeing here.

**Pull request closed without merging**
