### PR TITLE
Fix #719: UnicodeEncodingError in FacetGrid

### LINKED ISSUE #719: FacetGrid gives UnicodeEncodeError when data contains utf-8 characters
When labeling facets or labels in grids on the IPython notebook (using Python 2), an UnicodeEncodeError is raised.

Minimal example:

```
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
data = sns.load_dataset('anscombe')
data['dataset_unicode'] = data.dataset.map(lambda x: u'ÁéÍóÚ {0}'.format(x))
# works
g = sns.FacetGrid(data, col='dataset')
g.map(plt.scatter, 'x', 'y')
# doesn't work
g = sns.FacetGrid(data, col='dataset_unicode')
g.map(plt.scatter, 'x', 'y')
```

This raises the following exception:
```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-20-03ef1de0f907> in <module>()
     10 # doesn't work
     11 g = sns.FacetGrid(data, col='dataset_unicode', col_wrap=2)
---> 12 g.map(plt.scatter, 'x', 'y')

/home/egraells/envs/ipython/local/lib/python2.7/site-packages/seaborn/axisgrid.pyc in map(self, func, *args, **kwargs)
    727 
    728         # Finalize the annotations and layout
--> 729         self._finalize_grid(args[:2])
    730 
    731         return self

/home/egraells/envs/ipython/local/lib/python2.7/site-packages/seaborn/axisgrid.pyc in _finalize_grid(self, axlabels)
    817         """Finalize the annotations and layout."""
    818         self.set_axis_labels(*axlabels)
--> 819         self.set_titles()
    820         self.fig.tight_layout()
    821 

/home/egraells/envs/ipython/local/lib/python2.7/site-packages/seaborn/axisgrid.pyc in set_titles(self, template, row_template, col_template, **kwargs)
    959             for i, col_name in enumerate(self.col_names):
    960                 args.update(dict(col_name=col_name))
--> 961                 title = template.format(**args)
    962                 # Index the flat array so col_wrap works
    963                 self.axes.flat[i].set_title(title, **kwargs)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```

The same happens when using the hue parameter. For instance, this is the error (copy-paste from a real situation):
```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-197-516653d44a94> in <module>()
      1 g = sns.FacetGrid(viajes, hue='Relacion', col='ModoAgregado', col_wrap=3, aspect=2)
----> 2 g.map(sns.distplot, 'start_time', kde=True, hist=False)
      3 g.add_legend()

/home/egraells/envs/ipython/local/lib/python2.7/site-packages/seaborn/axisgrid.pyc in map(self, func, *args, **kwargs)
    710             # Insert a label in the keyword arguments for the legend
    711             if self._hue_var is not None:
--> 712                 kwargs["label"] = str(self.hue_names[hue_k])
    713 
    714             # Get the actual data we are going to plot with

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 1: ordinal not in range(128)
```

Library versions:

 * matplotlib: 1.4.3
 * seaborn: 0.6.0

Using `%matplotlib inline%` in the IPython notebook.

### PR DESCRIPTION
**Pull request by gkunter**
These commits fix the Unicode-related issue #719 (see the commit messages for details). It may be possible that there are still more places in the code in which a conversion to Unicode is necessary.

### CODE REVIEW

**Comment by gkunter** [comment]
There is a typo in utils.py.

**Comment by mwaskom** [comment]
To be clear, in this comment:

> Under Python 2.7, all tests fail in FacetGrid.set_titles() in one of the lines containing the instruction ```title = template.format(**args)```.

do you mean the tests would fail without the addition of the `utils.to_utf8` conversion?

**Comment by gkunter** [comment]
Yes, exactly that: without this addition, a UnicodeEncodingError will be raised by the tests in Python 2.7 because ``FacetGrid.set_titles()`` attempts to format the Unicode string arguments with the format string ``template``, which is a byte string.

With this addition, no such exception is raised in Python 2.7. In Python 3.x, the tests will always pass, with or without the addition.

**Comment by mwaskom** [comment]
Great. Thanks, this is an excellent PR. Other unicode issues may pop up, but this will make it easier to handle them.

**Comment by gkunter** [comment]
Glad to help. I've had myself so many Unicode problems with a code base that is supposed to run both in Python 2.7 and Python 3.x that I've kind of learned how to deal with them. And I've learned to loath Python 2.7 for its horrible Unicode support in the process...

**Pull request merged**
