### PR TITLE
[DO NOT MERGE] Test pandas 1.3 release candidate

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Not to merge, but just to test the pandas release candidate on your CI.

### CODE REVIEW

**Comment by mwaskom** [comment]
Hm looks like pandas 1.3 is incompatible with seaborn's minimally supported version of statsmodels (0.9).

This won't actually break the seaborn CI once 1.3 is released because that build will run with a similarly pinned version of pandas.

Also 0.9 is ~3 years old now so I could bump that to 0.10 per NEP29.

**Comment by jorisvandenbossche** [comment]
And the build that did run with the latest versions is all passing without failures or warnings, so that looks good!

**Comment by mwaskom** [comment]
@jorisvandenbossche good to close?

**Comment by jorisvandenbossche** [comment]
Yes!

**Comment by mwaskom** [comment]
Great — good luck with the release!

**Pull request closed without merging**
