### PR TITLE
COMPAT: compat with mpl 1.5 color cycle

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/mwaskom/seaborn/issues/711 and #732 

One oddity here is if a user has modified their `axes.prop_cycler` to be a cycler that doesn't include the `color` key. In this case we just fall back to `axes.color_cycle` and they'll get the warning. I actually think the changes I made to pandas missed this possibility and will just break :shrug:.

For Travis, want me to modify one of the `testing/deps_modern`? https://anaconda.org/conda-forge/matplotlib/files has RC1... not sure about a more up to date version.

I've got a couple (seemingly unrelated) failures to cleanup too. They fail for me on master so I'm not sure if that's another mpl 1.5 thing or what. Not sure if I'll get to that any time soon.
For the record, those failures are

```
======================================================================
FAIL: seaborn.tests.test_matrix.TestDendrogram.test_dendrogram_ticklabel_rotation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/seaborn/seaborn/tests/test_matrix.py", line 579, in test_dendrogram_ticklabel_rotation
    nt.assert_equal(t.get_rotation(), 90)
AssertionError: 0.0 != 90

======================================================================
FAIL: seaborn.tests.test_matrix.TestHeatmap.test_heatmap_annotation_with_mask
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/seaborn/seaborn/tests/test_matrix.py", line 244, in test_heatmap_annotation_with_mask
    nt.assert_equal(len(df_masked[::-1].compressed()), len(ax.texts))
AssertionError: 7 != 1

======================================================================
FAIL: seaborn.tests.test_matrix.TestHeatmap.test_heatmap_ticklabel_rotation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/seaborn/seaborn/tests/test_matrix.py", line 301, in test_heatmap_ticklabel_rotation
    nt.assert_equal(t.get_rotation(), 90)
AssertionError: 0.0 != 90
```

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks! Look like the unrelated failures on Travis are Pandas 0.17 changes I haven't had time to fix. I *think* (but am not certain) that the heatmap failures you're seeing locally are issues with the MacOSX backend. If your'e running the tests with that backend, maybe try changing it and see if they go away?

**Comment by mwaskom** [comment]
> For Travis, want me to modify one of the testing/deps_modern? https://anaconda.org/conda-forge/matplotlib/files has RC1... not sure about a more up to date version.

I have ambitions to include a travis build for dev versions of matplotlib, pandas, etc., but I haven't had time to figure out how to make that work.

**Comment by TomAugspurger** [comment]
> I think (but am not certain) that the heatmap failures you're seeing locally are issues with the MacOSX backend

Do you have a pointer on how to ensure that gets set? I tried just hardcoding

```python
import matplotlib
matplotlib.use('agg')
```

at the top of `test_matrix.` But that still fails, and I still see the warning. Maybe it's being set again somewhere in the tests?

> I have ambitions to include a travis build for dev versions

I thought that we were uploading dev versions of pandas to https://anaconda.org/pandas/pandas, I think in the `dev` channel (I'm not familiar with how conda channels work). Not sure about matplotlib's dev builds.

Let me look into the other failures quick.

**Comment by mwaskom** [comment]
> Do you have a pointer on how to ensure that gets set?

If you do [`make test`](https://github.com/mwaskom/seaborn/blob/master/Makefile#L3) it will copy in a local `matploltlibrc` that should set the backend properly.

**Comment by mwaskom** [comment]
> I thought that we were uploading dev versions of pandas to https://anaconda.org/pandas/pandas, I think in the dev channel (I'm not familiar with how conda channels work). Not sure about matplotlib's dev builds.

At some point, Travis (Oliphant, not the service) tweeting something new in conda that made me think "hey that will make it easier to test against the bleeding edge", but I have since lost track of what that was :/

**Comment by TomAugspurger** [comment]
The pandas failure seems to be a regression on our part where we don't parse `pd.date_range('Jan 1'...)` any more. Issue here: https://github.com/pydata/pandas/issues/11430.

Restarted travis with the doctest changed to be `pd.date_range('2015-01-01'...)`. Python3 versions passed (yay) but python 2 failed (will look later, have to run for now).

There's a chance I'll have time this afternoon to submit a PR fixing the `.order`/`.sort` warnings to use the new versions if people have 0.17 installed. Sorry about that, but hopefully you see that the old way was a horrible mess.

**Comment by mwaskom** [comment]
According to Jeff that was never supposed to be valid (https://github.com/mwaskom/seaborn/issues/702) :). Fortunately it's just usage in a doctest and so not really a problem in seaborn.

Anyway clearly I've been negligent in making things work recently, definitely appreciate the help keeping things compatible.

**Comment by TomAugspurger** [comment]
Yay Travis is green. It did fail once with statsmodels raising a PerfectSeparationError on one of the `test_logistic` tests.

And as far as I can tell, the library itself doesn't use `.sort` or `.order` anywhere, just in the documentation. I thought I saw a warning once when making a plot, but it could have been my code. I'll keep a closer watch for it to see if I can get a reproducible example.

Oh and I removed a SettingWithCopy warning; that one's on the house :)

**Comment by mwaskom** [comment]
Oops, accidentally commited the local matplotlib rc into the root of the repo, which I think is probably fine but might cause problems.

**Comment by mwaskom** [comment]
Otherwise looks great, thanks!

**Comment by TomAugspurger** [comment]
Sorry about that, just repushed without it.

Want me to change anything on the CI side? It's been a while since I've messed with Travis stuff and it wasn't immediately obvious how I would get the dev versions running :/

**Comment by mwaskom** [comment]
No worries on that front for now, I'll try to remember to look into it soon.

Alternatively pandas could just stop changing :)

**Comment by TomAugspurger** [comment]
Yeah, like *that* will ever happen.

**Comment by mwaskom** [comment]
Thanks again!

**Comment by mhooreman** [comment]
Hello,

Do you know when that fix will be released?

Thanks a lot.

**Comment by mwaskom** [comment]
It's unlikely that I will have time to do a release until the winter holiday, but in the meantime you can just use the code on the master branch..

**Comment by AlJohri** [comment]
thanks for this! would love to see a release soon :+1:

**Comment by TomAugspurger** [comment]
@AlJohri thankfully seaborn is pure python, so once you have the dependencies installed, getting the dev version of seaborn is relatively straightforward.

FWIW Michael let me know if there's anything I can do to help cut a release. But I get that you've got bigger things going on :)

**Comment by mwaskom** [comment]
I will do a release when I have time to do one. As Tom said, it's easy to install the development version if the warning bothers you (e.g. `pip install git+git://github.com/mwaskom/seaborn.git`)

Also since I see some confusion about this on StackOverflow, etc., and a lot of people end up on this page, I just want to clarify that the deprecation warning about `color_cycle` is just a *warning* that code using `color_cycle` will break at some point *in the future*. Seaborn 0.6 is fully compatible with matplotlib 1.5, but it will not be compatible with some future version of matplotlib that removes the backwards compatibility layer. The warnings message can certainly be annoying, but it's not a sign that anything is not working at the moment.

**Pull request merged**
