### PR TITLE
Standardize cache directory

### PR DESCRIPTION
**Pull request by Freed-Wu**
Fix https://github.com/mwaskom/seaborn/issues/1530

### CODE REVIEW

**Comment by mwaskom** [comment]
Please put this file in the `external/` directory with other vendored packages and include a copy of its license in the `licenses/` directory. And please fill out the PR description to link to previous discussions and close related issues.

**Comment by Freed-Wu** [comment]
Fix #1530

**Comment by mwaskom** [comment]
Thanks @Freed-Wu , you need to put the "closes #issue" in the first post otherwise it won't link properly. I edited the PR description to do that.

**Comment by mwaskom** [comment]
Thanks @Freed-Wu, I did a little fixup and then merged locally. In the future, please

- Make changes on a branch, rather than on your version of `master`
- Take a moment to look at the context around the change you are making for opening the PR; I had to fix the docstring to the `get_data_home` function that you edited, which had a reference to the previous cache location.

**Comment by Freed-Wu** [comment]
Thanks!

**Comment by mightyCelu** [comment]
Thanks for this PR @Freed-Wu !

**Pull request merged**
