### PR TITLE
Add support for per-category width on boxplot.

### PR DESCRIPTION
**Pull request by elmer-garduno**
Support per-category width on boxplot. As discused on https://github.com/mwaskom/seaborn/issues/1668, this is done by passing an array of widths on the sns.boxplot(width) argument.

Please let me know if this makes sense. I can add further testing.

### CODE REVIEW

**Comment by mwaskom** [comment]
I think that if this were going to be supported, it would have to be similar to how that option works in violinplot.

**Comment by elmer-garduno** [comment]
Thanks, you mean in terms of preserving the area? Or in terms of
automatically using the number of samples to determine the relative width?

**Comment by elmer-garduno** [comment]
I see, do you mean using the scale parameter instead and preserve the
semantics of weight as they are?

If so that makes sense, let me try it.

**Comment by mwaskom** [comment]
This is now obviated (without explicit effort to enable it) by #3294:

```python
sns.boxplot(data=tips, x="day", y="total_bill", widths=[.2, .4, .6, .8])
```


It doesn't work with `hue`; enabling that would be rather difficult and I lean not worth it.

Thanks for your interest!

**Pull request closed without merging**
